names:
- '1'
- '10'
- '100'
- '1000'
- '20'
- '200'
- '5'
- '50'
- '500'
nc: 9
roboflow:
  license: CC BY 4.0
  project: philippine-money-hjn3v
  url: https://universe.roboflow.com/philippine-money-jczbl/philippine-money-hjn3v/dataset/1
  version: 1
  workspace: philippine-money-jczbl
test: C:\pesoscan\backend\Philippine-Money-1\test\images
train: C:\pesoscan\backend\Philippine-Money-1\train\images
val: C:\pesoscan\backend\Philippine-Money-1\valid\images
